# Generated by Django 6.0.2 on 2026-02-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название курса', max_length=150, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='materials/preview/course', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Напишите описание курса', null=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название урока', max_length=150, verbose_name='Название урока')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='materials/preview/lesson', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Напишите описание урока', null=True, verbose_name='Описание урока')),
                ('link_video', models.URLField(blank=True, help_text='Прикрепите ссылку на видео', null=True, verbose_name='Ссылка')),
                ('course', models.ForeignKey(help_text='Укажите курс', on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
