# Generated by Django 6.0.2 on 2026-04-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Введите цену курса', verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Введите цену курса', verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
